logging:
  level:
    org.springframework.cloud.function: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    function:
      definition: homeViewComponent

viewcomponent:
  localDevelopment: true